version: '3.9'
services:
  ealy-mongo:
    image: mongo:4.4.6-bionic
    container_name: ealy-mongodb
    ports:
    - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=ealydev
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    networks:
      - ealy-net
  mongo-express:
    image: mongo-express:0.54.0
    container_name: ealy-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=ealy-mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
    networks:
      - ealy-net


networks:
  ealy-net: